name: Update Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          GHREF: ${{ github.ref }}
        run: |
          set -eux

          case "$GHREF" in
          refs/heads/master)    IMAGE=backend-setoko ;;
          refs/heads/staging) IMAGE=backend-setoko-staging ;;
          *) echo "unknow git ref target" >&2 && exit 1 ;;
          esac

          # prepare ssh master and port forward
          printf %s\\n "$SSH_PRIVATE_KEY" > .github/ssh_key
          chmod 0600 .github/ssh_key
          ssh_master=(
            -o "StrictHostKeyChecking accept-new"
            -o "ControlMaster yes"
            -o "ControlPath $PWD/.github/ssh_control"
            -o "ConnectTimeout 1000"
            -i "$PWD/.github/ssh_key"
            -NTf -L 5000:127.0.0.1:5000
            "$REMOTE_USER@$REMOTE_HOST"
          )
          ssh_slave=(
            -o "ControlPath $PWD/.github/ssh_control"
            "$REMOTE_USER@$REMOTE_HOST"
          )
          ssh "${ssh_master[@]}"

          # update it
          ssh "${ssh_slave[@]}" ./app-docker/$IMAGE/app rotate_and_update
